services:
  db-backup:
    build:
      context: .
      dockerfile: Dockerfile

    image: quarm-backup

    env_file:
      - .env
    volumes:
      - ./database_backups:/app/backups
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - "-user=${DB_USER}"
      - "-pass=${DB_PASS}"
      - "-db=${DB_NAME}"
      - "-host=${DB_HOST}"
      - "-port=${DB_PORT}"
      - "-dir=/app/backups"
      - "-t=${BACKUP_MINUTES}"

    restart: unless-stopped
